#ifndef ANALYZEREPORT_H
#define ANALYZEREPORT_H

#include <QDialog>  // Include Qt dialog base class

namespace Ui {
class analyzereport;  // Forward declaration of UI class generated by Qt Designer
}

class analyzereport : public QDialog
{
    Q_OBJECT  // Qt macro for enabling signals and slots mechanism

public:
    explicit analyzereport(QWidget *parent = nullptr);  // Constructor with optional parent widget
    ~analyzereport();  // Destructor

private slots:
    void onBackButtonClicked();  // Slot for handling back button click event
    void onFilterClicked();      // Slot for handling filter button click event
    void generatePieChart(const QString &month, int year);  // Slot/function to generate pie chart based on month and year

private:
    Ui::analyzereport *ui;  // Pointer to UI elements for this dialog
};

#endif // ANALYZEREPORT_H
