#ifndef MONTHLYGOALS_H
#define MONTHLYGOALS_H

// Include QDialog, the base class for dialog windows in Qt
#include <QDialog>

// Declare the Ui namespace and the monthlygoals class inside it
// This is generated automatically from the .ui file by Qt's uic tool
namespace Ui {
class monthlygoals;
}

// monthlygoals class definition, derived from QDialog
class monthlygoals : public QDialog
{
    Q_OBJECT  // Enables Qt's signal-slot mechanism and other meta-object features

public:
    // Constructor - initializes the dialog window, optionally with a parent
    explicit monthlygoals(QWidget *parent = nullptr);

    // Destructor - used to clean up resources
    ~monthlygoals();

private slots:
    // Slot to handle when the "Submit" button is clicked
    void on_buttonSubmit_clicked();

private:
    // Pointer to the UI form generated by Qt Designer
    Ui::monthlygoals *ui;

    // Private method to display a message to the user
    void showMessage(const QString &msg);
};

#endif // MONTHLYGOALS_H
