#ifndef VIEWTRANSACTIONS_H
#define VIEWTRANSACTIONS_H

// Include QDialog, the base class for dialog windows in Qt
#include <QDialog>

// Forward declaration of the Ui class for viewtransactions,
// generated automatically from the .ui file by Qt's uic tool
namespace Ui {
class viewtransactions;
}

// viewtransactions class declaration, derived from QDialog
class viewtransactions : public QDialog
{
    Q_OBJECT  // Enables Qt’s signal-slot system and other meta-object features

public:
    // Constructor - initializes the viewtransactions dialog
    explicit viewtransactions(QWidget *parent = nullptr);

    // Destructor - cleans up any resources used by the dialog
    ~viewtransactions();

private:
    // Pointer to the UI form generated by Qt Designer
    Ui::viewtransactions *ui;

    // Function to load transaction data into a table or list in the UI
    void loadTransactionData();

    // Function to handle the "Back" button click event
    void onBackButtonClicked();
};

#endif // VIEWTRANSACTIONS_H
